### ISSUE TITLE
Don't strip trailing slashes from relay urls

### ISSUE THREAD

**Issue by davestgermain** [mikedilger/nostr-types#5]
[Stripping trailing slashes](https://github.com/mikedilger/nostr-types/blob/master/src/types/url.rs#L131) seems like a bug. In gossip, if I add a relay like `wss://some.host/path/`, the trailing slash gets stripped (which can be a problem if the server doesn't respond to both URLs), and then the NIP-11 request fails because it actually requests `https://some.host/`. I think slashes in the path of a url should always be preserved.

**Comment by mikedilger** [comment]
I agree there is a problem, I've known this for some time, but I haven't seen a solution that works well for all concerns.  I'm not satisfied with preserving slashes as a solution.

Strictly speaking, technically, the path "" is different from the path "/".  In practice, 99+% of relays serve the same content on "" as they do on "/".

This can also be said of "/path" and "/path/".

If we considered these different, then we would have practical problems such as this one:
1) User wants to follow a person on at least 2 relays for redundancy.
2) The client chooses "wss://xyz.example.com/" and "wss://xyz.example.com" and thinks it is getting redundancy.

Now maybe gossip needs to make a distinction between the relay host and the relay URL endpoint.  If it did, then redundancy requires different hosts, and relay statistics like success/fail can be applied per-host not per-url.  But it then seems like we will probably never actually run into two distinct relays running on the same host, so it seems like a waste to even bother.

The real world mess is that data inside of nostr events often has the same relay with and without the slash, and we would be doubling our relay dataset, which doesn't accurately represent what is actually going on.

**Comment by mikedilger** [comment]
BTW The nip11 request going to the host has nothing to do with the slash being stripped, and everything to do with ignoring the path entirely. So that's a separate thing (in gossip, not this crate).

**Comment by mikedilger** [comment]
and I have just fixed this on master.

**Comment by davestgermain** [comment]
> BTW The nip11 request going to the host has nothing to do with the slash being stripped, and everything to do with ignoring the path entirely. So that's a separate thing (in gossip, not this crate).

Thanks. Good to hear. That bug was my motivation for reporting, after I saw the errors in the console.

As far as the slash goes, generally I've seen web frameworks have a feature to automatically add slashes. For instance, a request for `/nostr` gets redirected to `/nostr/`. `wss://xyz.example.com/` is the canonical URL; if you leave off the slash, either the browser or any web server will redirect the request. 

But I've not seen web frameworks strip slashes. It's probably safe to assume that if somebody adds a slash, they know what they're doing, whereas if they leave off the slash, they're either being imprecise/lazy or don't know that there's a difference.

I understand that the real world data is messy. It's up to you how you want to normalize it. My suggestion is to add slashes if the user specifies a URL at the root path, otherwise don't alter it. The root path should be the only special case.

Either way, I've configured my server to respond to `/nostr` and `/nostr/`, so this issue is not a big deal for me.

**Comment by mikedilger** [comment]
So you think "https://example.com/RomeoAndJuliet.pdf/" is the canonical URL for "https://example.com/RomeoAndJulet.pdf". That's entertaining.

**Comment by davestgermain** [comment]
> So you think "https://example.com/RomeoAndJuliet.pdf/" is the canonical URL for "https://example.com/RomeoAndJulet.pdf". That's entertaining.

No, I said the canonical URI for the *root path* is `/`.

**Comment by mikedilger** [comment]
Sorry I misunderstood. But your earlier post suggested "/nostr gets redirected to /nostr/" which is fine if the server that is authoritative for the URLs does it (which is the point I missed), but it is not fine for a client to do it.

https://www.rfc-editor.org/rfc/rfc3986 has a section on normalization.  The rust http crate has a Uri type which has no normalization functionality.  I might have to write a URL normalization crate because the ones I'm looking at don't do it right, or don't go far enough. The trailing slash is just the tip of the iceberg.

**Comment by mikedilger** [comment]
Ok it looks like the Url crate does a lot of this normalization (but not the http::Uri crate), for example

````
    let url = Url::parse("wss://example.com").unwrap();
    assert_eq!(url.as_str(), "wss://example.com/");
````

That part will be easy. The conversion of existing data part will be a bitch.
