### ISSUE TITLE
Use a workspace to seprate types from binary

### ISSUE THREAD

**Issue by thesimplekid** [mikedilger/nostr-types#9]
What do you thing of separating moving the types into a sub crate with the types separated from the binary? This would let other projects use the types without the larger dependencies of the binary, specifically reqwest and tungstenite which are not necessarily needed depending on what the other project is doing.

**Comment by mikedilger** [comment]
Yeah, I need another crate. I don't think I'll bother with a workspace.  I have a bunch of additional binaries in an unpublished crate that are really "edit and compile before you run because they don't accept user input, you just hardcode variables".. which is why it is not published.

**Comment by mikedilger** [comment]
Ok I stripped them out. I created a 'nostr-bins' repo.  Did this quite fast, let me know if anything broke that you notice.

**Comment by thesimplekid** [comment]
Awesome, thanks
